version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # or 16 if you prefer
    commands:
      - echo Installing dependencies...
      - cd src
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build

artifacts:
  files:  
    - dist/**/*
  base-directory: src
  discard-paths: yes
