version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source NPM dependencies...
      - cd src
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Node.js app...
      - npm run build
artifacts:
  files:  
    - src/**/dist/**/*
  base-directory: src 
  discard-paths: yes